/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKYWEAVE_V2_SKYWEAVE_PB_H_INCLUDED
#define PB_SKYWEAVE_V2_SKYWEAVE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* D0 section 3. The string values in `contracts/enums.py` are the frozen
 wire-stable names; these numbers are the D7 wire encoding of the same set,
 in the order D0's table lists them. proto3 requires a zero value, which is
 deliberately UNSPECIFIED: a datagram that omits the domain decodes to
 UNSPECIFIED and is REJECTED, never silently defaulted to a real clock. */
typedef enum _skyweave_v2_ClockDomain {
    skyweave_v2_ClockDomain_CLOCK_DOMAIN_UNSPECIFIED = 0,
    skyweave_v2_ClockDomain_CLOCK_DOMAIN_SYNTHETIC = 1,
    skyweave_v2_ClockDomain_CLOCK_DOMAIN_NODE_MONO = 2,
    skyweave_v2_ClockDomain_CLOCK_DOMAIN_NODE_PTP = 3,
    skyweave_v2_ClockDomain_CLOCK_DOMAIN_JETSON_RX = 4
} skyweave_v2_ClockDomain;

typedef enum _skyweave_v2_EvidenceKind {
    skyweave_v2_EvidenceKind_EVIDENCE_KIND_UNSPECIFIED = 0,
    skyweave_v2_EvidenceKind_EVIDENCE_KIND_PATCH_Y8 = 1, /* packed 8-bit luma crop */
    skyweave_v2_EvidenceKind_EVIDENCE_KIND_MASK_RLE = 2 /* run-length foreground mask */
} skyweave_v2_EvidenceKind;

typedef enum _skyweave_v2_ControlType {
    skyweave_v2_ControlType_CONTROL_TYPE_UNSPECIFIED = 0,
    skyweave_v2_ControlType_CONTROL_TYPE_START = 1,
    skyweave_v2_ControlType_CONTROL_TYPE_STOP = 2,
    skyweave_v2_ControlType_CONTROL_TYPE_SET_CONFIG = 3,
    skyweave_v2_ControlType_CONTROL_TYPE_CALIBRATION_REVISION = 4,
    skyweave_v2_ControlType_CONTROL_TYPE_ACK = 5
} skyweave_v2_ControlType;

/* Struct definitions */
/* D0 section 4. Field numbers 1-15 are the D0 reservation, verbatim.

 PRECISION NOTE (D7 finding): D0's type column declares fields 6, 7, 8 and
 15 `float`, i.e. IEEE-754 binary32, while the pydantic model holds Python
 doubles. Values that are not exactly representable in binary32 therefore
 change on the wire. This file follows the frozen D0 declaration rather than
 widening the field; `codec.py` documents the measured consequence and
 `transport/report.py` reports it. */
typedef struct _skyweave_v2_FrameEnvelope {
    uint32_t camera_id;
    char session_uuid[37]; /* per node boot (D0 section 3) */
    uint64_t frame_seq; /* per session */
    int64_t capture_ts_ns; /* EXPOSURE MIDPOINT (D0 decision) */
    skyweave_v2_ClockDomain clock_domain;
    float time_sync_error_ms; /* honest, may be large */
    float exposure_us;
    float gain_db;
    uint32_t full_width;
    uint32_t full_height;
    uint32_t proc_width; /* detector grid (F2) */
    uint32_t proc_height;
    char calibration_rev[65]; /* hash of estimator calibration */
    char detector_rev[65]; /* detector build/config hash */
    float line_readout_us; /* rolling-shutter row time */
} skyweave_v2_FrameEnvelope;

/* D0 field 8: "bbox | x0,y0,w,h | full-res px". Carried as a bounded
 sub-message so nanopb allocates it inline; x/y are zigzag because a bbox
 origin may sit off the left/top edge of the sensor grid. */
typedef struct _skyweave_v2_BoundingBox {
    int32_t x;
    int32_t y;
    uint32_t w;
    uint32_t h;
} skyweave_v2_BoundingBox;

/* D0 section 4. Field numbers 1-13 are the D0 reservation, verbatim.

 Field 1 (`envelope`) is D0's "FrameEnvelope OR REFERENCE TO ONE". Inside an
 ObservationPacket the envelope is carried ONCE at packet level and field 1
 MUST be unset; a set field 1 inside a packet is a hard decode error, never
 a silent override (see codec.decode_observation_packet). The field stays
 declared here so a standalone Observation2D remains representable and so
 number 1 can never be reused for anything else. */
typedef struct _skyweave_v2_Observation2D {
    bool has_envelope;
    skyweave_v2_FrameEnvelope envelope;
    uint32_t obs_id;
    double u; /* full-res calibrated px (D0 section 2) */
    double v;
    double cov_uu; /* full-res px^2, never zero */
    double cov_uv;
    double cov_vv;
    bool has_bbox;
    skyweave_v2_BoundingBox bbox;
    uint32_t area_px; /* at proc resolution */
    uint32_t persistence_count;
    float confidence; /* detector-internal, not a probability */
    bool has_local_blob_id;
    uint32_t local_blob_id; /* explicit presence: absent != 0 */
    bool has_evidence_ref;
    char evidence_ref[65]; /* droppable mask/crop id */
} skyweave_v2_Observation2D;

/* One capture event, one datagram (D0 section 10 "D7 opening"). The envelope
 appears once; the observations reference it by position, not by copy.
 `observations` is bounded (see skyweave.options) and measurement data NEVER
 splits across datagrams: an event that does not fit the ceiling is a loud
 encode failure, not a fragment. */
typedef struct _skyweave_v2_ObservationPacket {
    bool has_envelope;
    skyweave_v2_FrameEnvelope envelope;
    pb_size_t observations_count;
    skyweave_v2_Observation2D observations[7];
} skyweave_v2_ObservationPacket;

typedef PB_BYTES_ARRAY_T(8192) skyweave_v2_EvidencePacket_payload_t;
/* Optional evidence for one observation. Travels on its own socket so it can
 be dropped under congestion without touching a measurement, and carries an
 explicit expiry so a late patch is discarded rather than re-opening a
 solved batch. Losing all of these must change no geometry input (T7/W3). */
typedef struct _skyweave_v2_EvidencePacket {
    char evidence_ref[65]; /* matches Observation2D.evidence_ref */
    uint32_t camera_id;
    char session_uuid[37];
    uint64_t frame_seq;
    int64_t capture_ts_ns;
    int64_t expiry_ts_ns; /* evidence-drop rule: expire, never block */
    skyweave_v2_EvidenceKind kind;
    int32_t x0; /* crop origin, full-res px */
    int32_t y0;
    uint32_t width;
    uint32_t height;
    skyweave_v2_EvidencePacket_payload_t payload;
} skyweave_v2_EvidencePacket;

/* D0 section 1: "Quaternions (xyzw) exist only at the viz boundary and are
 derived, never authoritative." The IMU quaternion below is exactly that:
 mount-orientation telemetry, never an estimator input. */
typedef struct _skyweave_v2_Quaternion {
    double x;
    double y;
    double z;
    double w;
} skyweave_v2_Quaternion;

typedef struct _skyweave_v2_HealthPacket {
    uint32_t camera_id;
    char session_uuid[37];
    int64_t ts_ns;
    skyweave_v2_ClockDomain clock_domain;
    double fps;
    uint64_t drops;
    double time_sync_error_ms;
    bool has_imu_quaternion;
    skyweave_v2_Quaternion imu_quaternion;
} skyweave_v2_HealthPacket;

typedef struct _skyweave_v2_CalibrationRevision {
    char calibration_rev[65];
    char detector_rev[65];
} skyweave_v2_CalibrationRevision;

typedef struct _skyweave_v2_NodeConfig {
    uint32_t proc_width;
    uint32_t proc_height;
    double target_fps;
    uint32_t max_observations_per_packet;
    bool evidence_enabled;
} skyweave_v2_NodeConfig;

typedef struct _skyweave_v2_Ack {
    uint64_t control_seq; /* the control_seq being acknowledged */
    bool accepted;
    char detail[129]; /* labeled reason when accepted == false */
} skyweave_v2_Ack;

/* A discriminated wrapper rather than a `oneof`: nanopb allocates every
 declared sub-message statically, and a C daemon switching on an enum is
 simpler to audit than a synthetic union. Exactly one payload sub-message is
 set for a given `type`; a mismatch is a loud decode error. */
typedef struct _skyweave_v2_ControlMessage {
    skyweave_v2_ControlType type;
    uint64_t control_seq;
    char session_uuid[37];
    uint32_t camera_id;
    bool has_calibration;
    skyweave_v2_CalibrationRevision calibration;
    bool has_config;
    skyweave_v2_NodeConfig config;
    bool has_ack;
    skyweave_v2_Ack ack;
} skyweave_v2_ControlMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _skyweave_v2_ClockDomain_MIN skyweave_v2_ClockDomain_CLOCK_DOMAIN_UNSPECIFIED
#define _skyweave_v2_ClockDomain_MAX skyweave_v2_ClockDomain_CLOCK_DOMAIN_JETSON_RX
#define _skyweave_v2_ClockDomain_ARRAYSIZE ((skyweave_v2_ClockDomain)(skyweave_v2_ClockDomain_CLOCK_DOMAIN_JETSON_RX+1))

#define _skyweave_v2_EvidenceKind_MIN skyweave_v2_EvidenceKind_EVIDENCE_KIND_UNSPECIFIED
#define _skyweave_v2_EvidenceKind_MAX skyweave_v2_EvidenceKind_EVIDENCE_KIND_MASK_RLE
#define _skyweave_v2_EvidenceKind_ARRAYSIZE ((skyweave_v2_EvidenceKind)(skyweave_v2_EvidenceKind_EVIDENCE_KIND_MASK_RLE+1))

#define _skyweave_v2_ControlType_MIN skyweave_v2_ControlType_CONTROL_TYPE_UNSPECIFIED
#define _skyweave_v2_ControlType_MAX skyweave_v2_ControlType_CONTROL_TYPE_ACK
#define _skyweave_v2_ControlType_ARRAYSIZE ((skyweave_v2_ControlType)(skyweave_v2_ControlType_CONTROL_TYPE_ACK+1))

#define skyweave_v2_FrameEnvelope_clock_domain_ENUMTYPE skyweave_v2_ClockDomain




#define skyweave_v2_EvidencePacket_kind_ENUMTYPE skyweave_v2_EvidenceKind


#define skyweave_v2_HealthPacket_clock_domain_ENUMTYPE skyweave_v2_ClockDomain




#define skyweave_v2_ControlMessage_type_ENUMTYPE skyweave_v2_ControlType


/* Initializer values for message structs */
#define skyweave_v2_FrameEnvelope_init_default   {0, "", 0, 0, _skyweave_v2_ClockDomain_MIN, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define skyweave_v2_BoundingBox_init_default     {0, 0, 0, 0}
#define skyweave_v2_Observation2D_init_default   {false, skyweave_v2_FrameEnvelope_init_default, 0, 0, 0, 0, 0, 0, false, skyweave_v2_BoundingBox_init_default, 0, 0, 0, false, 0, false, ""}
#define skyweave_v2_ObservationPacket_init_default {false, skyweave_v2_FrameEnvelope_init_default, 0, {skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default, skyweave_v2_Observation2D_init_default}}
#define skyweave_v2_EvidencePacket_init_default  {"", 0, "", 0, 0, 0, _skyweave_v2_EvidenceKind_MIN, 0, 0, 0, 0, {0, {0}}}
#define skyweave_v2_Quaternion_init_default      {0, 0, 0, 0}
#define skyweave_v2_HealthPacket_init_default    {0, "", 0, _skyweave_v2_ClockDomain_MIN, 0, 0, 0, false, skyweave_v2_Quaternion_init_default}
#define skyweave_v2_CalibrationRevision_init_default {"", ""}
#define skyweave_v2_NodeConfig_init_default      {0, 0, 0, 0, 0}
#define skyweave_v2_Ack_init_default             {0, 0, ""}
#define skyweave_v2_ControlMessage_init_default  {_skyweave_v2_ControlType_MIN, 0, "", 0, false, skyweave_v2_CalibrationRevision_init_default, false, skyweave_v2_NodeConfig_init_default, false, skyweave_v2_Ack_init_default}
#define skyweave_v2_FrameEnvelope_init_zero      {0, "", 0, 0, _skyweave_v2_ClockDomain_MIN, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define skyweave_v2_BoundingBox_init_zero        {0, 0, 0, 0}
#define skyweave_v2_Observation2D_init_zero      {false, skyweave_v2_FrameEnvelope_init_zero, 0, 0, 0, 0, 0, 0, false, skyweave_v2_BoundingBox_init_zero, 0, 0, 0, false, 0, false, ""}
#define skyweave_v2_ObservationPacket_init_zero  {false, skyweave_v2_FrameEnvelope_init_zero, 0, {skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero, skyweave_v2_Observation2D_init_zero}}
#define skyweave_v2_EvidencePacket_init_zero     {"", 0, "", 0, 0, 0, _skyweave_v2_EvidenceKind_MIN, 0, 0, 0, 0, {0, {0}}}
#define skyweave_v2_Quaternion_init_zero         {0, 0, 0, 0}
#define skyweave_v2_HealthPacket_init_zero       {0, "", 0, _skyweave_v2_ClockDomain_MIN, 0, 0, 0, false, skyweave_v2_Quaternion_init_zero}
#define skyweave_v2_CalibrationRevision_init_zero {"", ""}
#define skyweave_v2_NodeConfig_init_zero         {0, 0, 0, 0, 0}
#define skyweave_v2_Ack_init_zero                {0, 0, ""}
#define skyweave_v2_ControlMessage_init_zero     {_skyweave_v2_ControlType_MIN, 0, "", 0, false, skyweave_v2_CalibrationRevision_init_zero, false, skyweave_v2_NodeConfig_init_zero, false, skyweave_v2_Ack_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define skyweave_v2_FrameEnvelope_camera_id_tag  1
#define skyweave_v2_FrameEnvelope_session_uuid_tag 2
#define skyweave_v2_FrameEnvelope_frame_seq_tag  3
#define skyweave_v2_FrameEnvelope_capture_ts_ns_tag 4
#define skyweave_v2_FrameEnvelope_clock_domain_tag 5
#define skyweave_v2_FrameEnvelope_time_sync_error_ms_tag 6
#define skyweave_v2_FrameEnvelope_exposure_us_tag 7
#define skyweave_v2_FrameEnvelope_gain_db_tag    8
#define skyweave_v2_FrameEnvelope_full_width_tag 9
#define skyweave_v2_FrameEnvelope_full_height_tag 10
#define skyweave_v2_FrameEnvelope_proc_width_tag 11
#define skyweave_v2_FrameEnvelope_proc_height_tag 12
#define skyweave_v2_FrameEnvelope_calibration_rev_tag 13
#define skyweave_v2_FrameEnvelope_detector_rev_tag 14
#define skyweave_v2_FrameEnvelope_line_readout_us_tag 15
#define skyweave_v2_BoundingBox_x_tag            1
#define skyweave_v2_BoundingBox_y_tag            2
#define skyweave_v2_BoundingBox_w_tag            3
#define skyweave_v2_BoundingBox_h_tag            4
#define skyweave_v2_Observation2D_envelope_tag   1
#define skyweave_v2_Observation2D_obs_id_tag     2
#define skyweave_v2_Observation2D_u_tag          3
#define skyweave_v2_Observation2D_v_tag          4
#define skyweave_v2_Observation2D_cov_uu_tag     5
#define skyweave_v2_Observation2D_cov_uv_tag     6
#define skyweave_v2_Observation2D_cov_vv_tag     7
#define skyweave_v2_Observation2D_bbox_tag       8
#define skyweave_v2_Observation2D_area_px_tag    9
#define skyweave_v2_Observation2D_persistence_count_tag 10
#define skyweave_v2_Observation2D_confidence_tag 11
#define skyweave_v2_Observation2D_local_blob_id_tag 12
#define skyweave_v2_Observation2D_evidence_ref_tag 13
#define skyweave_v2_ObservationPacket_envelope_tag 1
#define skyweave_v2_ObservationPacket_observations_tag 2
#define skyweave_v2_EvidencePacket_evidence_ref_tag 1
#define skyweave_v2_EvidencePacket_camera_id_tag 2
#define skyweave_v2_EvidencePacket_session_uuid_tag 3
#define skyweave_v2_EvidencePacket_frame_seq_tag 4
#define skyweave_v2_EvidencePacket_capture_ts_ns_tag 5
#define skyweave_v2_EvidencePacket_expiry_ts_ns_tag 6
#define skyweave_v2_EvidencePacket_kind_tag      7
#define skyweave_v2_EvidencePacket_x0_tag        8
#define skyweave_v2_EvidencePacket_y0_tag        9
#define skyweave_v2_EvidencePacket_width_tag     10
#define skyweave_v2_EvidencePacket_height_tag    11
#define skyweave_v2_EvidencePacket_payload_tag   12
#define skyweave_v2_Quaternion_x_tag             1
#define skyweave_v2_Quaternion_y_tag             2
#define skyweave_v2_Quaternion_z_tag             3
#define skyweave_v2_Quaternion_w_tag             4
#define skyweave_v2_HealthPacket_camera_id_tag   1
#define skyweave_v2_HealthPacket_session_uuid_tag 2
#define skyweave_v2_HealthPacket_ts_ns_tag       3
#define skyweave_v2_HealthPacket_clock_domain_tag 4
#define skyweave_v2_HealthPacket_fps_tag         5
#define skyweave_v2_HealthPacket_drops_tag       6
#define skyweave_v2_HealthPacket_time_sync_error_ms_tag 7
#define skyweave_v2_HealthPacket_imu_quaternion_tag 8
#define skyweave_v2_CalibrationRevision_calibration_rev_tag 1
#define skyweave_v2_CalibrationRevision_detector_rev_tag 2
#define skyweave_v2_NodeConfig_proc_width_tag    1
#define skyweave_v2_NodeConfig_proc_height_tag   2
#define skyweave_v2_NodeConfig_target_fps_tag    3
#define skyweave_v2_NodeConfig_max_observations_per_packet_tag 4
#define skyweave_v2_NodeConfig_evidence_enabled_tag 5
#define skyweave_v2_Ack_control_seq_tag          1
#define skyweave_v2_Ack_accepted_tag             2
#define skyweave_v2_Ack_detail_tag               3
#define skyweave_v2_ControlMessage_type_tag      1
#define skyweave_v2_ControlMessage_control_seq_tag 2
#define skyweave_v2_ControlMessage_session_uuid_tag 3
#define skyweave_v2_ControlMessage_camera_id_tag 4
#define skyweave_v2_ControlMessage_calibration_tag 5
#define skyweave_v2_ControlMessage_config_tag    6
#define skyweave_v2_ControlMessage_ack_tag       7

/* Struct field encoding specification for nanopb */
#define skyweave_v2_FrameEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   camera_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   session_uuid,      2) \
X(a, STATIC,   SINGULAR, UINT64,   frame_seq,         3) \
X(a, STATIC,   SINGULAR, INT64,    capture_ts_ns,     4) \
X(a, STATIC,   SINGULAR, UENUM,    clock_domain,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    time_sync_error_ms,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    exposure_us,       7) \
X(a, STATIC,   SINGULAR, FLOAT,    gain_db,           8) \
X(a, STATIC,   SINGULAR, UINT32,   full_width,        9) \
X(a, STATIC,   SINGULAR, UINT32,   full_height,      10) \
X(a, STATIC,   SINGULAR, UINT32,   proc_width,       11) \
X(a, STATIC,   SINGULAR, UINT32,   proc_height,      12) \
X(a, STATIC,   SINGULAR, STRING,   calibration_rev,  13) \
X(a, STATIC,   SINGULAR, STRING,   detector_rev,     14) \
X(a, STATIC,   SINGULAR, FLOAT,    line_readout_us,  15)
#define skyweave_v2_FrameEnvelope_CALLBACK NULL
#define skyweave_v2_FrameEnvelope_DEFAULT NULL

#define skyweave_v2_BoundingBox_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, SINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   w,                 3) \
X(a, STATIC,   SINGULAR, UINT32,   h,                 4)
#define skyweave_v2_BoundingBox_CALLBACK NULL
#define skyweave_v2_BoundingBox_DEFAULT NULL

#define skyweave_v2_Observation2D_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  envelope,          1) \
X(a, STATIC,   SINGULAR, UINT32,   obs_id,            2) \
X(a, STATIC,   SINGULAR, DOUBLE,   u,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   v,                 4) \
X(a, STATIC,   SINGULAR, DOUBLE,   cov_uu,            5) \
X(a, STATIC,   SINGULAR, DOUBLE,   cov_uv,            6) \
X(a, STATIC,   SINGULAR, DOUBLE,   cov_vv,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bbox,              8) \
X(a, STATIC,   SINGULAR, UINT32,   area_px,           9) \
X(a, STATIC,   SINGULAR, UINT32,   persistence_count,  10) \
X(a, STATIC,   SINGULAR, FLOAT,    confidence,       11) \
X(a, STATIC,   OPTIONAL, UINT32,   local_blob_id,    12) \
X(a, STATIC,   OPTIONAL, STRING,   evidence_ref,     13)
#define skyweave_v2_Observation2D_CALLBACK NULL
#define skyweave_v2_Observation2D_DEFAULT NULL
#define skyweave_v2_Observation2D_envelope_MSGTYPE skyweave_v2_FrameEnvelope
#define skyweave_v2_Observation2D_bbox_MSGTYPE skyweave_v2_BoundingBox

#define skyweave_v2_ObservationPacket_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  envelope,          1) \
X(a, STATIC,   REPEATED, MESSAGE,  observations,      2)
#define skyweave_v2_ObservationPacket_CALLBACK NULL
#define skyweave_v2_ObservationPacket_DEFAULT NULL
#define skyweave_v2_ObservationPacket_envelope_MSGTYPE skyweave_v2_FrameEnvelope
#define skyweave_v2_ObservationPacket_observations_MSGTYPE skyweave_v2_Observation2D

#define skyweave_v2_EvidencePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   evidence_ref,      1) \
X(a, STATIC,   SINGULAR, UINT32,   camera_id,         2) \
X(a, STATIC,   SINGULAR, STRING,   session_uuid,      3) \
X(a, STATIC,   SINGULAR, UINT64,   frame_seq,         4) \
X(a, STATIC,   SINGULAR, INT64,    capture_ts_ns,     5) \
X(a, STATIC,   SINGULAR, INT64,    expiry_ts_ns,      6) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              7) \
X(a, STATIC,   SINGULAR, SINT32,   x0,                8) \
X(a, STATIC,   SINGULAR, SINT32,   y0,                9) \
X(a, STATIC,   SINGULAR, UINT32,   width,            10) \
X(a, STATIC,   SINGULAR, UINT32,   height,           11) \
X(a, STATIC,   SINGULAR, BYTES,    payload,          12)
#define skyweave_v2_EvidencePacket_CALLBACK NULL
#define skyweave_v2_EvidencePacket_DEFAULT NULL

#define skyweave_v2_Quaternion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x,                 1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y,                 2) \
X(a, STATIC,   SINGULAR, DOUBLE,   z,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   w,                 4)
#define skyweave_v2_Quaternion_CALLBACK NULL
#define skyweave_v2_Quaternion_DEFAULT NULL

#define skyweave_v2_HealthPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   camera_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   session_uuid,      2) \
X(a, STATIC,   SINGULAR, INT64,    ts_ns,             3) \
X(a, STATIC,   SINGULAR, UENUM,    clock_domain,      4) \
X(a, STATIC,   SINGULAR, DOUBLE,   fps,               5) \
X(a, STATIC,   SINGULAR, UINT64,   drops,             6) \
X(a, STATIC,   SINGULAR, DOUBLE,   time_sync_error_ms,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu_quaternion,    8)
#define skyweave_v2_HealthPacket_CALLBACK NULL
#define skyweave_v2_HealthPacket_DEFAULT NULL
#define skyweave_v2_HealthPacket_imu_quaternion_MSGTYPE skyweave_v2_Quaternion

#define skyweave_v2_CalibrationRevision_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   calibration_rev,   1) \
X(a, STATIC,   SINGULAR, STRING,   detector_rev,      2)
#define skyweave_v2_CalibrationRevision_CALLBACK NULL
#define skyweave_v2_CalibrationRevision_DEFAULT NULL

#define skyweave_v2_NodeConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proc_width,        1) \
X(a, STATIC,   SINGULAR, UINT32,   proc_height,       2) \
X(a, STATIC,   SINGULAR, DOUBLE,   target_fps,        3) \
X(a, STATIC,   SINGULAR, UINT32,   max_observations_per_packet,   4) \
X(a, STATIC,   SINGULAR, BOOL,     evidence_enabled,   5)
#define skyweave_v2_NodeConfig_CALLBACK NULL
#define skyweave_v2_NodeConfig_DEFAULT NULL

#define skyweave_v2_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   control_seq,       1) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          2) \
X(a, STATIC,   SINGULAR, STRING,   detail,            3)
#define skyweave_v2_Ack_CALLBACK NULL
#define skyweave_v2_Ack_DEFAULT NULL

#define skyweave_v2_ControlMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT64,   control_seq,       2) \
X(a, STATIC,   SINGULAR, STRING,   session_uuid,      3) \
X(a, STATIC,   SINGULAR, UINT32,   camera_id,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  calibration,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ack,               7)
#define skyweave_v2_ControlMessage_CALLBACK NULL
#define skyweave_v2_ControlMessage_DEFAULT NULL
#define skyweave_v2_ControlMessage_calibration_MSGTYPE skyweave_v2_CalibrationRevision
#define skyweave_v2_ControlMessage_config_MSGTYPE skyweave_v2_NodeConfig
#define skyweave_v2_ControlMessage_ack_MSGTYPE skyweave_v2_Ack

extern const pb_msgdesc_t skyweave_v2_FrameEnvelope_msg;
extern const pb_msgdesc_t skyweave_v2_BoundingBox_msg;
extern const pb_msgdesc_t skyweave_v2_Observation2D_msg;
extern const pb_msgdesc_t skyweave_v2_ObservationPacket_msg;
extern const pb_msgdesc_t skyweave_v2_EvidencePacket_msg;
extern const pb_msgdesc_t skyweave_v2_Quaternion_msg;
extern const pb_msgdesc_t skyweave_v2_HealthPacket_msg;
extern const pb_msgdesc_t skyweave_v2_CalibrationRevision_msg;
extern const pb_msgdesc_t skyweave_v2_NodeConfig_msg;
extern const pb_msgdesc_t skyweave_v2_Ack_msg;
extern const pb_msgdesc_t skyweave_v2_ControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define skyweave_v2_FrameEnvelope_fields &skyweave_v2_FrameEnvelope_msg
#define skyweave_v2_BoundingBox_fields &skyweave_v2_BoundingBox_msg
#define skyweave_v2_Observation2D_fields &skyweave_v2_Observation2D_msg
#define skyweave_v2_ObservationPacket_fields &skyweave_v2_ObservationPacket_msg
#define skyweave_v2_EvidencePacket_fields &skyweave_v2_EvidencePacket_msg
#define skyweave_v2_Quaternion_fields &skyweave_v2_Quaternion_msg
#define skyweave_v2_HealthPacket_fields &skyweave_v2_HealthPacket_msg
#define skyweave_v2_CalibrationRevision_fields &skyweave_v2_CalibrationRevision_msg
#define skyweave_v2_NodeConfig_fields &skyweave_v2_NodeConfig_msg
#define skyweave_v2_Ack_fields &skyweave_v2_Ack_msg
#define skyweave_v2_ControlMessage_fields &skyweave_v2_ControlMessage_msg

/* Maximum encoded size of messages (where known) */
#define SKYWEAVE_V2_SKYWEAVE_PB_H_MAX_SIZE       skyweave_v2_EvidencePacket_size
#define skyweave_v2_Ack_size                     144
#define skyweave_v2_BoundingBox_size             24
#define skyweave_v2_CalibrationRevision_size     132
#define skyweave_v2_ControlMessage_size          370
#define skyweave_v2_EvidencePacket_size          8364
#define skyweave_v2_FrameEnvelope_size           244
#define skyweave_v2_HealthPacket_size            124
#define skyweave_v2_NodeConfig_size              29
#define skyweave_v2_Observation2D_size           413
#define skyweave_v2_ObservationPacket_size       3159
#define skyweave_v2_Quaternion_size              36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
