/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "skyweave.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(skyweave_v2_FrameEnvelope, skyweave_v2_FrameEnvelope, AUTO)


PB_BIND(skyweave_v2_BoundingBox, skyweave_v2_BoundingBox, AUTO)


PB_BIND(skyweave_v2_Observation2D, skyweave_v2_Observation2D, 2)


PB_BIND(skyweave_v2_ObservationPacket, skyweave_v2_ObservationPacket, 2)


PB_BIND(skyweave_v2_EvidencePacket, skyweave_v2_EvidencePacket, 4)


PB_BIND(skyweave_v2_Quaternion, skyweave_v2_Quaternion, AUTO)


PB_BIND(skyweave_v2_HealthPacket, skyweave_v2_HealthPacket, AUTO)


PB_BIND(skyweave_v2_CalibrationRevision, skyweave_v2_CalibrationRevision, AUTO)


PB_BIND(skyweave_v2_NodeConfig, skyweave_v2_NodeConfig, AUTO)


PB_BIND(skyweave_v2_Ack, skyweave_v2_Ack, AUTO)


PB_BIND(skyweave_v2_ControlMessage, skyweave_v2_ControlMessage, 2)









#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

